
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Mar 06 20:06:36 PST 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int t_for = 8;
  public static final int t_boolconstant = 41;
  public static final int t_void = 18;
  public static final int t_extends = 7;
  public static final int t_doubleconstant = 43;
  public static final int t_assignop = 31;
  public static final int t_return = 16;
  public static final int t_intconstant = 42;
  public static final int t_interface = 12;
  public static final int t_else = 6;
  public static final int t_implements = 10;
  public static final int t_if = 9;
  public static final int t_leftparen = 35;
  public static final int t_id = 45;
  public static final int t_semicolon = 32;
  public static final int t_readln = 15;
  public static final int t_lessequal = 26;
  public static final int t_mod = 24;
  public static final int t_stringconstant = 44;
  public static final int t_greaterequal = 28;
  public static final int t_rightparen = 36;
  public static final int t_minus = 21;
  public static final int t_division = 23;
  public static final int EOF = 0;
  public static final int t_greater = 27;
  public static final int error = 1;
  public static final int t_string = 17;
  public static final int t_println = 14;
  public static final int t_comma = 33;
  public static final int t_class = 4;
  public static final int t_notequal = 30;
  public static final int t_equal = 29;
  public static final int t_leftbracket = 37;
  public static final int t_less = 25;
  public static final int t_multiplication = 22;
  public static final int t_leftbrace = 39;
  public static final int t_break = 3;
  public static final int t_period = 34;
  public static final int t_rightbracket = 38;
  public static final int t_bool = 2;
  public static final int t_double = 5;
  public static final int t_rightbrace = 40;
  public static final int t_plus = 20;
  public static final int t_int = 11;
  public static final int t_newarray = 13;
  public static final int t_while = 19;
}

